services:
  backend:
    image: hieut3/backend-iot:latest
    container_name: backend-iot
    environment:
      DATASOURCE_URL: jdbc:mysql://mysql-iot:3306/systemdb
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: 123456
      CLOUDINARY_URL: cloudinary://819435846128484:aW7SyJov32jfgaRQzGvFEgSp1Ng@dpa03wf83
      JWT_SECRET_KEY: 1bbc3e3ab1a6ea6cef942c4dd24ecd8cf47dc0c488baf3b9c623f128f61992d7
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - iot

  mysql:
    image: mysql:latest
    container_name: mysql-iot
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: systemdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - iot

volumes:
  mysql-data:

networks:
  iot:
    name: iot


